- name: Install default tsafe tools
  become: yes
  apt:
    name: "{{ packages }}"
    update_cache: yes
    cache_valid_time: 1800
    state: present
  vars:
    packages:
    # Adding this package so that we always keep python3 up to date even if its already been installed
    - python3-minimal
    - curl
    - vim
    - wget
    - htop
    - tree
    - iputils-ping
    - netcat
    - ntp
    - jq
  tags:
    - packages
  
